import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navigation from "@/components/Navigation";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        {/* Decorative grid lines */}
        <div className="grid fixed inset-0">
          <div className="fixed top-8 md:top-20 w-full h-px bg-[#D9D9D9]/15" />
          <div className="fixed left-8 md:left-20 w-px h-full bg-[#D9D9D9]/15" />
          <div className="fixed right-8 md:right-20 w-px h-full bg-[#D9D9D9]/15" />
        </div>

        <Navigation />
        {children}
      </body>
    </html>
  );
}
