import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} min-h-screen bg-[#0F0F0F] antialiased`}
      >
        {/* Decorative grid lines */}
        <div className="fixed left-8 z-10 h-full w-px bg-[#D9D9D9]/15 md:left-11" />
        <div className="fixed right-8 z-10 h-full w-px bg-[#D9D9D9]/15 md:right-11" />
        <main>{children}</main>
      </body>
    </html>
  );
}
